module.exports.CONFIG = {
	ACCESS_SECRET: process.env.ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
	ALLOW_ORIGINS: process.env.ALLOWED_ORIGINS,
	MAX_FILE_SIZE: process.env.MAX_FILE_SIZE_IN_MB,
	MAX_FILE_LIMIT: process.env.MAX_FILE_COUNT,
	SERVER_PUBLIC_FOLDER: process.env.SERVER_PUBLIC_FOLDER,

};
